### PR TITLE
Missing ConfigureAwait(false) in CloudFileDirectory, Exceptions and StreamExtensions

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@danielmarbach__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@danielmarbach__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by erezvani1529** [comment]
Hi @danielmarbach,

Would you please target this PR to the Dev branch?

Thanks,
Elham

**Comment by danielmarbach** [comment]
Done

**Pull request merged**
