### PR TITLE
Prevent TestConfigurations.xml and creds from getting into repos

### PR DESCRIPTION
**Pull request by dbelcham**
This addresses #237 

Users will be able to find, in the README.md, how to create and name a local copy of the TestConfigurations.xml file that will then be used by test runs as the source for the Azure Storage container's credentials. The LocalTestConfigurations.xml file that they will create and enter their credentials into is part of the .gitignore so that it will not make it into repos.

### CODE REVIEW

**Comment by jehine-MSFT** [comment]
Hello @dbelcham ,

You can see here (#243) that we have fixed this problem by removing the file from the repo and adding it to the .gitignore file. All you have to do is add it back to get the tests to work, and you won't need to worry about uploading your creds while testing with this file again.

Thanks for the feedback!

**Comment by dbelcham** [comment]
So now a user has to either:
  a) know what the XML structure of the testconfiguration.xml file and create it themselves, or
  b) know which commit they have to go look at to find an example of this file and copy it from there

Either way you are putting a lot of burden on the user. This is a very high friction solution to the problem and anyone with zero history of working with this codebase will not be able to quickly figure this out. While you have solved one problem you have create another one that is just as bad.

**Comment by jehine-MSFT** [comment]
[https://github.com/Azure/azure-storage-net/blob/master/CONTRIBUTING.md#configuration](https://github.com/Azure/azure-storage-net/blob/master/CONTRIBUTING.md#configuration)

**Comment by jehine-MSFT** [comment]
Thank you for giving us feedback. We have published changes that will solve this issue making it much harder for developers to submit their credentials accidentally. Will close this issue.

**Pull request closed without merging**
