### PR TITLE
Storage Client Library 7.0.0

### PR DESCRIPTION
**Pull request by jehine-MSFT**

### CODE REVIEW

**Comment by GuardRex** [comment]
When this becomes available on NuGet, will this replace `6.2.2-preview`?

Environment: .NET Core via `dotnet cli` on Win10

**Comment by jehine-MSFT** [comment]
Hello @GuardRex,

This new and improved version of the lib should be out within next few days. .Net Core library will still be in preview as .Net Core has not GA'd yet. So be on the look out for 7.0.1-preview.

Thanks!

**Comment by jehine-MSFT** [comment]
Code is now live on [NuGet](https://www.nuget.org/packages/WindowsAzure.Storage)!

**Comment by pemari-msft** [comment]
Large Breaking Change for Windows RT 


As part of a larger effort to streamline the Azure Storage Client Library codebase, to support the latest Microsoft platforms, and to use and encourage best practices, there is a large breaking change for the Windows RT and Windows Store Universal platforms included in version 7.0 of our library. Previously, the signatures for service call methods returned an `IAsyncOperation` or `IAsyncAction` type in those targets. Moving forward, those signatures will return `Task` objects. This also fixes a known issue in the Portable Class Library when using our library with the above targets. We apologize to any customers that will have to change code for this break; if you need to convert your code from IAsync- to Task-based, here are some things to be aware of: 

* Both styles of return type can be `await`-ed. For much of your code, it may not require a change. 
* Tasks have the extension methods AsAsyncAction() and AsAsyncOperation() for quick conversion. 
* Streams may also require some change – please see the WindowsRuntimeStreamExtensions class if you need to convert streams.  
* IAsyncOperations have the extension method AsTask() for quick conversion. IAsyncActions have the extension method AsTask() for quick conversion. 

For example: 

``IAsyncOperation<bool> operation = container.ExistsAsync();``
``bool exists = operation.GetResults();``

can be adjusted to: 

``IAsyncOperation<bool> operation = container.ExistsAsync().AsAsyncOperation();``
``bool exists = operation.GetResults();``

while: 

``await container.FetchAttributesAsync();``

can remain the same. 


This change will not affect any existing versions of the library. You can find the list of all breaking changes in this version [here](https://github.com/Azure/azure-storage-net/blob/master/BreakingChanges.txt). As always, we appreciate any feedback you may have.  

 - The Azure Storage Team

**Pull request merged**
