### PR TITLE
FixMetadata and Pass Missing CancellationToken

### PR DESCRIPTION
**Pull request by davidrevoledo**
- Fix  a metadata in CloudBlob.StartCopyImpl
- Pass CancellationToken in `CloudBlobClient.ListBlobsSegmentedAsync`

Thanks.

### CODE REVIEW

**Comment by davidrevoledo** [comment]
Any news about it  ? thanks :)

**Comment by kfarmer-msft** [comment]
Thanks --

Taking these changes

**Comment by kfarmer-msft** [comment]
Please try v9.4.2

**Comment by davidrevoledo** [comment]
Awesome, I wanted to be contributor though, not a problem great thanks :) @kfarmer-msft

**Pull request closed without merging**
