### PR TITLE
Storage Client Library 5.0.2

### PR DESCRIPTION
**Pull request by pemari-msft**

### CODE REVIEW

**Comment by GuardRex** [comment]
The versioning of packages is difficult to understand and follow. For my .NET 5 Core CLR x64 beta6 projects, I was using `5.0.1-preview`. I see that there is a `5.0.3-preview`, and that will compile and run, so I've just switched over to that one. When I try `5.0.2`, the build fails with numerous type failures. It seems strange that `5.0.x-preview` works in .NET 5 but `5.0.2` doesn't. 

Are the packages that support .NET 5 always marked `-preview` right now? Are those the ones we .NET 5 jockeys need to exclusively concentrate on? If so, how will we know when to convert to non-preview versions? Is the versioning approach you are using documented somewhere?

**Comment by pemari-msft** [comment]
Our versioning follows the [semver](http://semver.org/) semantic. As documented in our [README.md](https://github.com/azure/azure-storage-net/) file:

>•ASP.NET 5 (DNX 4.5.1 and DNXCore 5.0, beta4): Storage Client Libraries for .NET are available to support ASP.NET 5 application development. This support is currently in preview. 
>•Portable Class Library Profile 111: Storage Client Libraries are available to support building PCL Profile 111 applications, as well as for Xamarin application development. This support is currently in preview.

The functionality that you're looking for is in preview. Thus, that functionality exists in our preview package, and only in our preview package (it is not yet ready for production environments). You can also check the nuget package to see what dlls exist in each package for each target, or go to our [nuget page](https://www.nuget.org/packages/WindowsAzure.Storage/5.0.3-preview) which shows the targets for each version. You can also check our changelog file if you're looking to see what changes are made in each version. 

When we GA our .NET 5 library, we'll make a public announcement, add the functionality to our non-preview version, update the readme, and add a relevant entry to the changelog file.

Could you share what part you found to be hard to discover so we can look to improve that area? We certainly want the process to be as easy as possible for our customers. Thanks!

**Comment by GuardRex** [comment]
Ah, yes. I understand it now, and I wish I had checked the NuGet page and compared 5.0.2 to 5.0.1-preview and 5.0.3-preview. That would have cleared it up for me. 

I can recommend the following changes to the README ...

1. Currently, the link to `NuGet` under the heading `Via NuGet` points to the generic www.nuget.org address. Change that to point directly at the current stable package at: https://www.nuget.org/packages/WindowsAzure.Storage/
2. Add a new heading `Versioning` and just state something to the effect that for .NET 5 dnx runtimes, we should only be using the `-preview` packages until we are informed that the stable releases have received the .NET 5 bits. I realize that the statement "This support is currently in preview" should be adequate to suggest the use of the `-preview` packages; but when my brain is fried from staring at code for 12 hours, things get past me.

**Comment by pemari-msft** [comment]
Cool, this is good feedback. We'll definitely fix the nuget link and we'll add a section where we specifically call out what is currently in preview to make it more explicit. Thanks again!

**Pull request merged**
