### PR TITLE
Removed unnecessary task scheduling inside HttpResponseAdapterMessage and DataServicesResponseAdapterMessage

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@danielmarbach__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by danielmarbach** [comment]
I signed the CLA

**Comment by danielmarbach** [comment]
Why has nobody ever looked at this, it seems that @erezvani1529 added milestones but those milestones are long passed?

**Comment by danielmarbach** [comment]
Pulled into https://github.com/Azure/azure-storage-net/pull/579

**Pull request closed without merging**
